---
language: python
python: "2.7"
sudo: required
dist: trusty

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-pip
  - sudo pip install ansible
  - sudo mkdir -p /opt/ansible_roles

install:
  - ansible --version
  - sudo ansible-galaxy install -p /opt/ansible_roles marvinpinto.docker
  - echo -e 'localhost ansible_connection=local' > tests/inventory
  - echo -e '[defaults]\nroles_path = ../:/opt/ansible_roles\nhostfile = ./tests/inventory' > ansible.cfg

script:
  - ansible-playbook --syntax-check tests/test.yml
  - ansible-playbook -v --diff tests/test.yml
  - >
    ansible-playbook tests/test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  irc:
    channels:
      - secure: "hhbFZu9TNTmjlaj4XSjI79UL6dTpNBh17uQDat0T5jgWtya/MBjtGy2wH8BzLZMvLhd8FbhjqZC1Cduv4+fenYKJzWJ9zEdWvqNGNcLWIHaju/1u+WFjGeD8rNF5NhC5YpqghEDCpi4F3k8fnBtcA+bKTughVX5CE6iYbFm2hag58JqteY08cKVtotgVQZPtXnGGtmKFSqNXOWkXyXjrl3VhuTg/Jlol0EkXvc5vUX+Vyb38MEC2gcLFxMsFs0RUkqxRXin7MFQOuhiuHUi3dkzVqKv49lliH5qD/jVPHZEhraTgJzsiuFFk+RnUBMOisOxqXf8PL8F58EVfaSX5EQrvOAOEDogs72pI+mQ9pNm/u6TNfv9Kwa05efHFzSXb2elMNfkjijwv+rhZlwhXWX0slLNKzmVIe+ALkinP+cN2h6UTrxFYV5+waLEXxMiOXMfOphkgBvfp/RQtBT/dY/20sfuixAFc0t+mFXkagrwUiOTs0oWj36LIaK/prr6JaW+3/RgNzSgpOAHBsWdAyF1OgIm6DpW2yBzK6YEZcQycRSYwhZp0iH9jCfi+jckn1fFB0yTfoyIQ72hy6l9MEM5mAuSWXW024WY2Cvxznm1YZ/2VfhHgRUIay1tuATWTz0VTsOBRKL55l3XV5YWR4mNR3mcNA35p8ZR6uOXdWc4="
    on_success: "change"
    on_failure: "change"
